travis:
  secure:
    BINSTAR_TOKEN: bD370eGpVftBPgvAwHZeewWKTPOfCDRLDHYko2F6H3M3yfMQkssXgn5+3fG32VRdASHy5NdtVCbTAXyte9p3qImL6611OYmMPCVPhsfLnHXpVuKcsdYBLxtrYbB7ZnAY27ylxHAeoMO9Pg7HYc2ZNufCCF4F+lnWMsdW/ICtY8xGam2CodIHkzx3vJNTSXjO5E3WGs22wLzYBWCMjwwemgBIAJjaHAGiP8h8vWBoXS81OksKXRTeS1YNW1G5cn3dBTVgilxaoG8JSQOTWoVBtp6poqWDlCgbJ+3cADITuc+IvKHi9MgiJ1ohoBanlteORIl43ye6MDJK+6e0JnvZgNCoa4GcMPUsvq5aO5xH7991uF8qyv+P/0xB/9zCvmh6NxafmBD5s0fap65v3crE6qh8EfBSiqpdfWkxUEF3a198eb/sHugy9peQ5jdfiY6s8bRsYO9dhBnsT4D7xua6/354NBIz4SIv1V6tPDjsTaZO0ZKC7GQpWDg89YKoJrAwU3Ch/TO0PsgTNpA5OOfTVOVuq2jfdR5o+v34ZTEQMhM2LjYVjFN9e3QD6sDTH8IzsE+tUPEMk88xuMlTBbIaaLaU0cfUjSvXbqWMSTxiud2VrQTRj/Xx6K/ZpJI7atmh1MwK5kuuWznIl+z1gRca6JvZIBG/W2JqsjX/YBwlRDc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
